spring:
  redis:
    database: 0
    host: 14.29.181.103
    port: 6379
    password:
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
    client-type: lettuce
lock:
 expire-time: 30